language: java

env:
  global:

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      sudo: true

cache:
  directories:
    - $HOME/.m2

install:
  - sudo apt install -y libzmq3-dev
  - cd ..
  - git clone https://github.com/zeromq/jzmq.git
  - cd jzmq/jzmq-jni
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd ../..
  - git clone -b javafx https://github.com/hanslovsky/imglib2-ui.git
  - cd imglib2-ui
  - mvn install
  - cd ..
  - git clone -b bigcat-javafx https://github.com/hanslovsky/bigdataviewer-core.git
  - cd bigdataviewer-core
  - mvn install
  - cd ..
  - git clone https://github.com/imglib/imglib2.git
  - cd imglib2
  - mvn install
  - cd ..
  - git clone git://github.com/ClearVolume/ClearGL.git ClearGL
  - cd ClearGL
  - mvn install
  - cd ..
  - git clone https://github.com/bigdataviewer/bigdataviewer-vistools.git
  - cd bigdataviewer-vistools
  - mvn install
  - cd ../bigcat

script: 
  - mvn clean install

