language: java

env:
  global:

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      sudo: false

cache:
  directories:
    - $HOME/.m2

install:
  - apt update
  - apt install -y openjfx
  - cd ..
  - git clone git://github.com/ClearVolume/ClearGL.git ClearGL
  - cd ClearGL
  - mvn install
  - cd ..
  - git clone -b RealARGBConverter-expose-alpha https://github.com/hanslovsky/imglib2.git
  - cd imglib2
  - mvn install
  - cd ..
  - git clone -b TransformAwareBufferedImageOverlayRenderer-with-background https://github.com/hanslovsky/bigdataviewer-core.git
  - cd bigdataviewer-core
  - mvn install
  - cd ..
  - git clone https://github.com/bigdataviewer/bigdataviewer-vistools.git
  - cd bigdataviewer-vistools
  - mvn install
  - cd ../bigcat

script: 
  - mvn clean install

#after_success:
#    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && mvn deploy --settings settings.xml
