- !mapping
  action: drag rotate slow
  contexts: [bdv]
# just something stupid, "not mapped" is not supported in current version of ui-behaviour
  triggers: [alt control shift SPACE button2]
- !mapping
  action: move annotation
  contexts: [bdv, bigcat]
  triggers: [control button1]
